# Generated by Django 5.0.1 on 2026-03-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='months',
            field=models.IntegerField(default=1),
        ),
    ]
